name: Schedule trigger
on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Run every 5 minutes
        run: echo "run every 5 minute"
